version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}A
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  api:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-net

  streamlit:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge
